#%- if not included %#
ci:
  autofix_commit_msg: "Pre-commit automatic fixes [...]"
  autoupdate_commit_msg: "Pre-commit automatic update"
default_install_hook_types:
- "pre-commit"
- "pre-push"
repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v4.5.0"
  hooks:
  - id: "trailing-whitespace"
    name: "Trim trailing whitespaces"
#%- else %#
- repo: "https://github.com/astral-sh/ruff-pre-commit"
  rev: "v0.1.14"
  hooks:
  - id: "ruff"
    name: "Run the Ruff linter"
    types_or: ["python", "pyi"]
    args: ["--fix"]
  - id: "ruff-format"
    name: "Run the Ruff formatter"
    types_or: ["python", "pyi"]
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v4.5.0"
  hooks:
  - id: "check-merge-conflict"
    args: ["--assume-in-merge"]
    name: "Check for merge conflicts"
    stages: ["push"]
- repo: "https://github.com/python-poetry/poetry"
#%- if False %#
  rev: "1.7.0"
#%- endif %#
  #% if True %#rev: "{{poetry_version}}"#% endif %#
  hooks:
  - id: "poetry-lock"
    stages: ["push"]
    name: "Run Poetry lock hook"
  - id: "poetry-check"
    stages: ["push"]
    name: "Run Poetry check hook"
#% endif %#
#%- if not included %#
- repo: "https://github.com/KyleKing/copier-template-tester"
  rev: "2.1.1"
  hooks:
  - id: "copier-template-tester"
    stages: ["push"]
    name: "Run Copier template tester"
    additional_dependencies: ["copier-templates-extensions"]
#%- endif %#