name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test
    strategy:
      matrix:
        python-major-version: [3]
        python-minor-version: [8, 9, 10, 11, 12]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {{ "${{ matrix.python-major-version }}.${{ matrix.python-minor-version }}" }}
      uses: actions/setup-python@v3
      with:
        python-version: '{{ "${{ matrix.python-major-version }}.${{ matrix.python-minor-version }}" }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests
      run: >-
        coverage run -m pytest -v .
    - name: Report coverage
      run: |
        coverage report
        coverage html --show-contexts --title "{{cookiecutter.repo_name}} coverage for {{ "${{ github.sha }}" }}"
    - name: Store coverage html
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html
        path: htmlcov