name: "Audit (skeleton)"

on: ["push"]

jobs:
  pip-audit:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Install Poetry"
      run: "pipx install poetry==1.7.1"
    - name: "Install the project"
      run: "poetry install"
    - name: "Set up Python location for pip-audit"
      shell: "bash"
      run: 'echo "PIPAPI_PYTHON_LOCATION=$(poetry env info -e)" >> $GITHUB_ENV'
    - name: "Audit"
      uses: "pypa/gh-action-pip-audit@v1.0.8"
